### ISSUE TITLE
error adding metadata to data object with grave character in the path

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_automated_ingest#100] opened 2019-09-03 12:37 UTC
Using v0.3.7.

When scanning an NFS-mounted directory, and gathering metadata for every file found...

Full error log is here:
```json
{
  "task_id": "9994fa13-ce42-11e9-b20c-0aaaf8493372",
  "task": "sync_dir",
  "einfo": "<ExceptionInfo: CAT_UNKNOWN_FILE(None,)>",
  "path": "/full/path/to/dirwith`/subdir",
  "exc": "CAT_UNKNOWN_FILE(None,)",
  "traceback": [
    [
      "/home/irods/venv/lib/python3.4/site-packages/celery/app/trace.py",
      382,
      "trace_task",
      "R = retval = fun(*args, **kwargs)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/celery/app/trace.py",
      641,
      "__protected_call__",
      "return self.run(*args, **kwargs)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods_capability_automated_ingest/sync_task.py",
      388,
      "sync_files",
      "sync_entry(self, meta, \"file\", sync_irods.sync_data_from_file, sync_irods.sync_metadata_from_file)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods_capability_automated_ingest/sync_task.py",
      482,
      "sync_entry",
      "raise self.retry(max_retries=max_retries, exc=err, countdown=retry_countdown)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/celery/app/task.py",
      667,
      "retry",
      "raise_with_context(exc)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods_capability_automated_ingest/sync_task.py",
      474,
      "sync_entry",
      "datafunc(meta2, logger, True)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods_capability_automated_ingest/sync_irods.py",
      415,
      "sync_data_from_file",
      "call(hdlr_mod, \"on_data_obj_create\", register_file, logger, hdlr_mod, logger, session, meta, **options)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods_capability_automated_ingest/sync_utils.py",
      147,
      "call",
      "getattr(hdlr_mod, hdlr)(func, *args, **options)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods_capability_automated_ingest/core.py",
      10,
      "on_data_obj_create",
      "cls.post_data_obj_create(*args, **options)"
    ],
    [
      "/home/irods/test_register_replica_nfs-metadata.py",
      23,
      "post_data_obj_create",
      "obj.metadata.add(\"filesystem::perms\", s[0], '')"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods/meta.py",
      55,
      "add",
      "self._manager.add(self._model_cls, self._path, meta)"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods/manager/metadata_manager.py",
      70,
      "add",
      "response = conn.recv()"
    ],
    [
      "/home/irods/venv/lib/python3.4/site-packages/irods/connection.py",
      91,
      "recv",
      "raise get_exception_by_code(msg.int_info)"
    ]
  ],
  "job_name": "0903-test-nfs",
  "event": "failed_task",
  "logger": "irods_sync/0903-test-nfs.log/WARNING",
  "level": "error",
  "@timestamp": "2019-09-03T12:04:14.631275+00:00"
}
```

This is the relevant content of the event handler `test_register_replica_nfs-metadata.py`:
```python
    @staticmethod
    def post_data_obj_create(hdlr_mod, logger, session, meta, **options):
        args = ['stat', '--printf', '%04a,%u,%U,%g,%G,%x,%y', meta['path']]
        out, err = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        s = str(out.decode('UTF-8')).split(',')
#        print(s)
        obj = session.data_objects.get(meta['target'])
        obj.metadata.add("filesystem::perms", s[0], '')
        obj.metadata.add("filesystem::uid",   s[1], '')
        obj.metadata.add("filesystem::owner", s[2], '')
        obj.metadata.add("filesystem::gid",   s[3], '')
        obj.metadata.add("filesystem::group", s[4], '')
        obj.metadata.add("filesystem::atime", s[5], '')
        obj.metadata.add("filesystem::mtime", s[6], '')
```

**Comment by alanking** [comment] 2024-09-12 17:51
Using the changes in #267, I was unable to reproduce this issue. I'm not sure whether the changes there or some change in the last 5 years fixed this, but I think we just need a test for this.

**Comment by korydraughn** [comment] 2024-10-08 16:59
I'm pretty sure the handling of backtick and other characters was addressed by the work for https://github.com/irods/irods/issues/4132.

**Comment by trel** [comment] 2024-10-08 17:23
agreed, just need a test.

**Comment by alanking** [comment] 2024-10-08 17:52
Hmm... given that this is an issue in the server, do we really need to test this? If anything, this test should exist in the PRC if not the server itself since the issue stemmed from an event handler's PRC call...

That being said, I already wrote the test, so, it's not a problem to add it. Maybe unnecessary testing time, though.

**Comment by trel** [comment] 2024-10-08 17:54
agreed, might be overkill... but let's just include it.    confidence is good.

**Closed** 2024-10-08 18:30 UTC
Labels: bug, needs-test
