### ISSUE TITLE
Ingest only possible as the rods user by default

### ISSUE THREAD

**Issue by holtgrewe** [irods/irods_capability_automated_ingest#138] opened 2020-11-23 15:57 UTC
The following snippet in `sync_irods.py` (and the lines below) require me to grant explicit read permissions to `/` and `/zoneName` to the ingest user. IOW: it's not particularly user friendly in the case that I want to have strict user separation instead of using the rods user everywhere.

```python
    # root collection must exist
    hdlr_mod = get_hdlr_mod(meta)
    session = irods_session(hdlr_mod, meta, logger)
    if not session.collections.exists('/'):
        raise Exception("Root collection does not exist")
```

Is this intended?

**Comment by alanking** [comment] 2020-11-23 17:07
I believe this is the same issue as #114. This has been reverted on master. Guess we are due for a release soon, huh? :)

**Comment by trel** [comment] 2020-12-10 20:54
closing as duplicate of #114

**Closed by trel** 2020-12-10 20:54 UTC
Labels: bug
